name: NereusOpus
main: hamsteryds.nereusopus.NereusOpus
version: 3.0.0

author:
  - 白熊
  - TwiShimmer
  - IceAge666
  - 关怀他人
  - xiaozhangup
api-version: 1.18
load: STARTUP

depend:
  - PlaceholderAPI
  - ProtocolLib
softdepend:
  - Citizens
  - InteractionVisualizer
  - AureliumSkills
  - HuskSync
  - ItemsAdder

commands:
  nereusopus: